name: Validate New Links

on: issues

jobs:
  validate:
    if: contains(github.event.issue.labels.*.name, 'content/link')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install
      - name: View issue information
        run: |
          echo "Issue id: ${{ github.event.issue.id }}"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"